apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-10-24T13:53:13Z"
  generation: 3
  labels:
    app: rethinkdb
  name: rethinkdb
  namespace: default
  resourceVersion: "105833"
  selfLink: /apis/apps/v1/namespaces/default/deployments/rethinkdb
  uid: ee9b3884-c980-4069-b18e-2b714544a1ae
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rethinkdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rethinkdb
    spec:
      containers:
      - image: gcr.io/cloudfamilymanager/github.com/min44/rethinkdb:702c596
        imagePullPolicy: IfNotPresent
        name: rethinkdb-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-10-24T13:53:13Z"
    lastUpdateTime: "2020-10-24T13:53:15Z"
    message: ReplicaSet "rethinkdb-579cd5b94b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-10-24T13:54:47Z"
    lastUpdateTime: "2020-10-24T13:54:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
